/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_htyuan_jnitest_TestActivity */

#ifndef _Included_com_htyuan_jnitest_TestActivity
#define _Included_com_htyuan_jnitest_TestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_htyuan_jnitest_TestActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_htyuan_jnitest_TestActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_htyuan_jnitest_TestActivity
 * Method:    unimplementedStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_htyuan_jnitest_TestActivity_unimplementedStringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_htyuan_jnitest_TestActivity
 * Method:    bussearcher_stattext
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_htyuan_jnitest_TestActivity_bussearcher_1stattext
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
